/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dil
 */
public class Calculator extends javax.swing.JFrame {

    private boolean zerodisp;
    private boolean desdisp;
    private boolean dgrrad;
    private boolean shift;

    private byte op;

    private double ina;
    private double inb;
    private double out;

    public Calculator() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton11 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        txtDisplay1 = new javax.swing.JTextField();
        txtDisplay2 = new javax.swing.JTextField();
        btnMemory = new javax.swing.JButton();
        btnMemorySave = new javax.swing.JButton();
        btnMemoryClear = new javax.swing.JButton();
        txtmemoryDisplay = new javax.swing.JTextField();
        rdoDagrees = new javax.swing.JRadioButton();
        btnRadians = new javax.swing.JRadioButton();
        btnPercent = new javax.swing.JButton();
        btnOneDividedByx = new javax.swing.JButton();
        btnSin = new javax.swing.JButton();
        btnCos = new javax.swing.JButton();
        btnTan = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        btnSeven = new javax.swing.JButton();
        btnEight = new javax.swing.JButton();
        btnNine = new javax.swing.JButton();
        btnSquare = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnEqual = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnFour = new javax.swing.JButton();
        btnFive = new javax.swing.JButton();
        btnSix = new javax.swing.JButton();
        btnSquareRoot = new javax.swing.JButton();
        btnSubstrac = new javax.swing.JButton();
        btnZero = new javax.swing.JButton();
        btnDecPoint = new javax.swing.JButton();
        btnNegace = new javax.swing.JButton();
        btnCubedRoot = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();
        btnOne = new javax.swing.JButton();
        btnTwo = new javax.swing.JButton();
        btnThree = new javax.swing.JButton();
        btnCubed = new javax.swing.JButton();
        btnMultiply = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        TbtnShift = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dilz Calculator");
        setResizable(false);

        txtDisplay1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txtDisplay1.setText("  0");
        txtDisplay1.setBorder(null);
        txtDisplay1.setFocusable(false);
        txtDisplay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDisplay1ActionPerformed(evt);
            }
        });

        txtDisplay2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txtDisplay2.setBorder(null);
        txtDisplay2.setFocusable(false);

        btnMemory.setBackground(new java.awt.Color(153, 153, 255));
        btnMemory.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnMemory.setText("MR");
        btnMemory.setBorder(null);
        btnMemory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMemory.setFocusable(false);
        btnMemory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemoryActionPerformed(evt);
            }
        });

        btnMemorySave.setBackground(new java.awt.Color(153, 153, 255));
        btnMemorySave.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnMemorySave.setText("MS");
        btnMemorySave.setBorder(null);
        btnMemorySave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMemorySave.setFocusable(false);
        btnMemorySave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemorySaveActionPerformed(evt);
            }
        });

        btnMemoryClear.setBackground(new java.awt.Color(153, 153, 255));
        btnMemoryClear.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnMemoryClear.setText("MC");
        btnMemoryClear.setBorder(null);
        btnMemoryClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMemoryClear.setFocusable(false);
        btnMemoryClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemoryClearActionPerformed(evt);
            }
        });

        txtmemoryDisplay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtmemoryDisplay.setText("  0");
        txtmemoryDisplay.setBorder(null);
        txtmemoryDisplay.setFocusable(false);
        txtmemoryDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmemoryDisplayActionPerformed(evt);
            }
        });

        rdoDagrees.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroup1.add(rdoDagrees);
        rdoDagrees.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rdoDagrees.setSelected(true);
        rdoDagrees.setText("Degrees");
        rdoDagrees.setBorder(null);
        rdoDagrees.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rdoDagrees.setFocusable(false);
        rdoDagrees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoDagreesActionPerformed(evt);
            }
        });

        btnRadians.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroup1.add(btnRadians);
        btnRadians.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnRadians.setText("Radians");
        btnRadians.setBorder(null);
        btnRadians.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRadians.setFocusable(false);
        btnRadians.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadiansActionPerformed(evt);
            }
        });

        btnPercent.setBackground(new java.awt.Color(153, 153, 255));
        btnPercent.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnPercent.setText("%");
        btnPercent.setBorder(null);
        btnPercent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPercent.setFocusable(false);
        btnPercent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPercentActionPerformed(evt);
            }
        });

        btnOneDividedByx.setBackground(new java.awt.Color(153, 153, 255));
        btnOneDividedByx.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnOneDividedByx.setText("1/x");
        btnOneDividedByx.setBorder(null);
        btnOneDividedByx.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOneDividedByx.setFocusable(false);
        btnOneDividedByx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOneDividedByxActionPerformed(evt);
            }
        });

        btnSin.setBackground(new java.awt.Color(153, 153, 255));
        btnSin.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnSin.setText("sin");
        btnSin.setBorder(null);
        btnSin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSin.setFocusable(false);
        btnSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinActionPerformed(evt);
            }
        });

        btnCos.setBackground(new java.awt.Color(153, 153, 255));
        btnCos.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnCos.setText("cos");
        btnCos.setBorder(null);
        btnCos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCos.setFocusable(false);
        btnCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCosActionPerformed(evt);
            }
        });

        btnTan.setBackground(new java.awt.Color(153, 153, 255));
        btnTan.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnTan.setText("tan");
        btnTan.setBorder(null);
        btnTan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTan.setFocusable(false);
        btnTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTanActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(153, 153, 255));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton10.setText("^");
        jButton10.setBorder(null);
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.setFocusable(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        btnSeven.setBackground(new java.awt.Color(153, 153, 255));
        btnSeven.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnSeven.setText("7");
        btnSeven.setBorder(null);
        btnSeven.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSeven.setFocusable(false);
        btnSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSevenActionPerformed(evt);
            }
        });

        btnEight.setBackground(new java.awt.Color(153, 153, 255));
        btnEight.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnEight.setText("8");
        btnEight.setBorder(null);
        btnEight.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEight.setFocusable(false);
        btnEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEightActionPerformed(evt);
            }
        });

        btnNine.setBackground(new java.awt.Color(153, 153, 255));
        btnNine.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnNine.setText("9");
        btnNine.setBorder(null);
        btnNine.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNine.setFocusable(false);
        btnNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNineActionPerformed(evt);
            }
        });

        btnSquare.setBackground(new java.awt.Color(153, 153, 255));
        btnSquare.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnSquare.setText("<html>x<sup>2</sup></html>");
        btnSquare.setBorder(null);
        btnSquare.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSquare.setFocusable(false);
        btnSquare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSquareActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(153, 153, 255));
        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnAdd.setText("+");
        btnAdd.setBorder(null);
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.setFocusable(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEqual.setBackground(new java.awt.Color(153, 153, 255));
        btnEqual.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnEqual.setText("=");
        btnEqual.setBorder(null);
        btnEqual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEqual.setFocusable(false);
        btnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(153, 153, 255));
        btnReset.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnReset.setText("C");
        btnReset.setBorder(null);
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.setFocusable(false);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnFour.setBackground(new java.awt.Color(153, 153, 255));
        btnFour.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnFour.setText("4");
        btnFour.setBorder(null);
        btnFour.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFour.setFocusable(false);
        btnFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFourActionPerformed(evt);
            }
        });

        btnFive.setBackground(new java.awt.Color(153, 153, 255));
        btnFive.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnFive.setText("5");
        btnFive.setBorder(null);
        btnFive.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFive.setFocusable(false);
        btnFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiveActionPerformed(evt);
            }
        });

        btnSix.setBackground(new java.awt.Color(153, 153, 255));
        btnSix.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnSix.setText("6");
        btnSix.setBorder(null);
        btnSix.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSix.setFocusable(false);
        btnSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSixActionPerformed(evt);
            }
        });

        btnSquareRoot.setBackground(new java.awt.Color(153, 153, 255));
        btnSquareRoot.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnSquareRoot.setText("<html>x<sup>1/2</sup></html>");
        btnSquareRoot.setBorder(null);
        btnSquareRoot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSquareRoot.setFocusable(false);
        btnSquareRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSquareRootActionPerformed(evt);
            }
        });

        btnSubstrac.setBackground(new java.awt.Color(153, 153, 255));
        btnSubstrac.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnSubstrac.setText("-");
        btnSubstrac.setBorder(null);
        btnSubstrac.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubstrac.setFocusable(false);
        btnSubstrac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubstracActionPerformed(evt);
            }
        });

        btnZero.setBackground(new java.awt.Color(153, 153, 255));
        btnZero.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnZero.setText("0");
        btnZero.setBorder(null);
        btnZero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnZero.setFocusable(false);
        btnZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZeroActionPerformed(evt);
            }
        });

        btnDecPoint.setBackground(new java.awt.Color(153, 153, 255));
        btnDecPoint.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnDecPoint.setText(".");
        btnDecPoint.setBorder(null);
        btnDecPoint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDecPoint.setFocusable(false);
        btnDecPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecPointActionPerformed(evt);
            }
        });

        btnNegace.setBackground(new java.awt.Color(153, 153, 255));
        btnNegace.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnNegace.setText("+-");
        btnNegace.setBorder(null);
        btnNegace.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNegace.setFocusable(false);
        btnNegace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNegaceActionPerformed(evt);
            }
        });

        btnCubedRoot.setBackground(new java.awt.Color(153, 153, 255));
        btnCubedRoot.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnCubedRoot.setText("<html>x<sup>1/3</sup></html>");
        btnCubedRoot.setBorder(null);
        btnCubedRoot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCubedRoot.setFocusable(false);
        btnCubedRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCubedRootActionPerformed(evt);
            }
        });

        btnDivide.setBackground(new java.awt.Color(153, 153, 255));
        btnDivide.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnDivide.setText("/");
        btnDivide.setBorder(null);
        btnDivide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDivide.setFocusable(false);
        btnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivideActionPerformed(evt);
            }
        });

        btnOne.setBackground(new java.awt.Color(153, 153, 255));
        btnOne.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnOne.setText("1");
        btnOne.setBorder(null);
        btnOne.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOne.setFocusable(false);
        btnOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOneActionPerformed(evt);
            }
        });

        btnTwo.setBackground(new java.awt.Color(153, 153, 255));
        btnTwo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnTwo.setText("2");
        btnTwo.setBorder(null);
        btnTwo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTwo.setFocusable(false);
        btnTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwoActionPerformed(evt);
            }
        });

        btnThree.setBackground(new java.awt.Color(153, 153, 255));
        btnThree.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnThree.setText("3");
        btnThree.setBorder(null);
        btnThree.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThree.setFocusable(false);
        btnThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThreeActionPerformed(evt);
            }
        });

        btnCubed.setBackground(new java.awt.Color(153, 153, 255));
        btnCubed.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnCubed.setText("<html>x<sup>3</sup></html>");
        btnCubed.setBorder(null);
        btnCubed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCubed.setFocusable(false);
        btnCubed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCubedActionPerformed(evt);
            }
        });

        btnMultiply.setBackground(new java.awt.Color(153, 153, 255));
        btnMultiply.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnMultiply.setText("*");
        btnMultiply.setBorder(null);
        btnMultiply.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMultiply.setFocusable(false);
        btnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplyActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(153, 153, 255));
        btnClear.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnClear.setText("CE");
        btnClear.setBorder(null);
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.setFocusable(false);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        TbtnShift.setBackground(new java.awt.Color(153, 153, 255));
        TbtnShift.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        TbtnShift.setText("Sh");
        TbtnShift.setBorder(null);
        TbtnShift.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TbtnShift.setFocusable(false);
        TbtnShift.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbtnShiftMouseClicked(evt);
            }
        });
        TbtnShift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TbtnShiftActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEight, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNine, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSquare, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMemory, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMemoryClear, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(btnMemorySave, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnEqual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDecPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNegace, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCubedRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSubstrac, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOne, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThree, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCubed, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFour, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFive, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSix, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSquareRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSin, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTan, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TbtnShift, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDisplay2)
                    .addComponent(txtDisplay1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdoDagrees)
                        .addGap(18, 18, 18)
                        .addComponent(btnRadians)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOneDividedByx, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtmemoryDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDisplay2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnMemorySave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMemoryClear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMemory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtmemoryDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOneDividedByx, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdoDagrees)
                    .addComponent(btnRadians))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TbtnShift, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnCos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSin, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnTan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnSeven, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNine, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSquare, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnFour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSquareRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCubed, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnZero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDecPoint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNegace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCubedRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSubstrac, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnClear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReset, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEqual, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TbtnShiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TbtnShiftActionPerformed

    }//GEN-LAST:event_TbtnShiftActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtDisplay1.setText("0");
        zerodisp = false;
        desdisp = false;
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnMemoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemoryActionPerformed
        txtDisplay1.setText(String.valueOf(txtmemoryDisplay.getText()));
    }//GEN-LAST:event_btnMemoryActionPerformed

    private void txtDisplay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDisplay1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDisplay1ActionPerformed

    private void btnCubedRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCubedRootActionPerformed
        inb = Double.parseDouble(String.valueOf(txtDisplay1.getText()));
        out = Math.sqrt(inb);

        txtDisplay1.setText(String.valueOf(out));
        txtDisplay2.setText("3/" + String.valueOf(inb));
        out = 0;
         op = 0;
    }//GEN-LAST:event_btnCubedRootActionPerformed

    private void btnNegaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNegaceActionPerformed
        ina = Double.parseDouble(String.valueOf(txtDisplay1.getText()));
        out = ina * -1;

        if (out > -100000000 && out < 100000000) {
            txtDisplay1.setText(String.valueOf(out));
        } else {
            txtDisplay1.setText("Error");
        }
        desdisp = true;
        out = 0;

    }//GEN-LAST:event_btnNegaceActionPerformed

    private void btnFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFourActionPerformed
        if (!zerodisp && !desdisp) {
            txtDisplay1.setText(null);
        }
        txtDisplay1.setText(txtDisplay1.getText() + "4");
        zerodisp = true;
    }//GEN-LAST:event_btnFourActionPerformed

    private void txtmemoryDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmemoryDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmemoryDisplayActionPerformed

    private void btnRadiansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadiansActionPerformed
        dgrrad = true;
    }//GEN-LAST:event_btnRadiansActionPerformed

    private void btnSquareRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSquareRootActionPerformed
        inb = Double.parseDouble(String.valueOf(txtDisplay1.getText()));
        out = Math.sqrt(inb);

        txtDisplay1.setText(String.valueOf(out));
        txtDisplay2.setText("/" + String.valueOf(inb));
        out = 0;
         op = 0;
    }//GEN-LAST:event_btnSquareRootActionPerformed

    private void btnZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZeroActionPerformed
        if (!zerodisp && !desdisp) {
            txtDisplay1.setText(null);
        }
        txtDisplay1.setText(txtDisplay1.getText() + "0");

    }//GEN-LAST:event_btnZeroActionPerformed

    private void btnOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOneActionPerformed
        if (!zerodisp && !desdisp) {
            txtDisplay1.setText(null);
        }
        txtDisplay1.setText(txtDisplay1.getText() + "1");
        zerodisp = true;
    }//GEN-LAST:event_btnOneActionPerformed

    private void btnTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwoActionPerformed
        if (!zerodisp && !desdisp) {
            txtDisplay1.setText(null);
        }
        txtDisplay1.setText(txtDisplay1.getText() + "2");
        zerodisp = true;
    }//GEN-LAST:event_btnTwoActionPerformed

    private void btnThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThreeActionPerformed
        if (!zerodisp && !desdisp) {
            txtDisplay1.setText(null);
        }
        txtDisplay1.setText(txtDisplay1.getText() + "3");
        zerodisp = true;
    }//GEN-LAST:event_btnThreeActionPerformed

    private void btnFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiveActionPerformed
        if (!zerodisp && !desdisp) {
            txtDisplay1.setText(null);
        }
        txtDisplay1.setText(txtDisplay1.getText() + "5");
        zerodisp = true;
    }//GEN-LAST:event_btnFiveActionPerformed

    private void btnSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSixActionPerformed
        if (!zerodisp && !desdisp) {
            txtDisplay1.setText(null);
        }
        txtDisplay1.setText(txtDisplay1.getText() + "6");
        zerodisp = true;
    }//GEN-LAST:event_btnSixActionPerformed

    private void btnSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSevenActionPerformed
        if (!zerodisp && !desdisp) {
            txtDisplay1.setText(null);
        }
        txtDisplay1.setText(txtDisplay1.getText() + "7");
        zerodisp = true;
    }//GEN-LAST:event_btnSevenActionPerformed

    private void btnEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEightActionPerformed
        if (!zerodisp && !desdisp) {
            txtDisplay1.setText(null);
        }
        txtDisplay1.setText(txtDisplay1.getText() + "8");
        zerodisp = true;
    }//GEN-LAST:event_btnEightActionPerformed

    private void btnNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNineActionPerformed
        if (!zerodisp && !desdisp) {
            txtDisplay1.setText(null);
        }
        txtDisplay1.setText(txtDisplay1.getText() + "9");
        zerodisp = true;
    }//GEN-LAST:event_btnNineActionPerformed

    private void btnDecPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecPointActionPerformed
        if (!desdisp) {
            txtDisplay1.setText(txtDisplay1.getText() + ".");
            desdisp = true;
        }
    }//GEN-LAST:event_btnDecPointActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtDisplay1.setText("0");
        txtDisplay2.setText(null);
        zerodisp = false;
        desdisp = false;
        ina = 0;
        inb = 0;
        out = 0;
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnMemoryClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemoryClearActionPerformed
        txtmemoryDisplay.setText("0");
    }//GEN-LAST:event_btnMemoryClearActionPerformed

    private void btnMemorySaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemorySaveActionPerformed
        txtmemoryDisplay.setText(String.valueOf(txtDisplay1.getText()));
    }//GEN-LAST:event_btnMemorySaveActionPerformed

    private void btnOneDividedByxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOneDividedByxActionPerformed
        inb = Double.parseDouble(String.valueOf(txtDisplay1.getText()));
        out = 1 / inb;

        if (out > -100000000 && out < 100000000) {
            txtDisplay1.setText(String.valueOf(out));
        } else {
            txtDisplay1.setText("Error");
        }

        txtDisplay2.setText("1/" + String.valueOf(inb));
        out = 0;
         op = 0;

    }//GEN-LAST:event_btnOneDividedByxActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        txtDisplay1.setText(String.valueOf(Math.PI));
    }//GEN-LAST:event_jButton10ActionPerformed

    private void btnSquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSquareActionPerformed
        inb = Double.parseDouble(String.valueOf(txtDisplay1.getText()));
        out = inb * inb;

        if (out > -100000000 && out < 100000000) {
            txtDisplay1.setText(String.valueOf(out));
        } else {
            txtDisplay1.setText("Error");
        }

        txtDisplay2.setText(String.valueOf(inb) + "2");
        out = 0;
         op = 0;

    }//GEN-LAST:event_btnSquareActionPerformed

    private void btnCubedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCubedActionPerformed
        inb = Double.parseDouble(String.valueOf(txtDisplay1.getText()));
        out = inb * inb * inb;

        if (out > -100000000 && out < 100000000) {
            txtDisplay1.setText(String.valueOf(out));
        } else {
            txtDisplay1.setText("Error");
        }

        txtDisplay2.setText(String.valueOf(inb) + "3");
        out = 0;
         op = 0;
    }//GEN-LAST:event_btnCubedActionPerformed

    private void TbtnShiftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbtnShiftMouseClicked
        if (!shift) {
            shift = true;
        } else {
            shift = false;
        }
    }//GEN-LAST:event_TbtnShiftMouseClicked

    private void btnSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinActionPerformed
        inb = Double.parseDouble(String.valueOf(txtDisplay1.getText()));
        if (!shift) {
            if (!dgrrad) {
                txtDisplay2.setText("sin( " + String.valueOf(inb) + ")");
                inb = inb * 0.0174532925;
            }
            out = Math.sin(inb);
        } else {
            txtDisplay2.setText("sinh( " + String.valueOf(inb) + ")");
            out = Math.sinh(inb);
        }
        txtDisplay1.setText(String.valueOf(out));
        
        out = 0;
        op = 0;
    }//GEN-LAST:event_btnSinActionPerformed

    private void btnCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCosActionPerformed
        inb = Double.parseDouble(String.valueOf(txtDisplay1.getText()));
        if (!shift) {
            if (!dgrrad) {
                txtDisplay2.setText("cos( " + String.valueOf(inb) + ")");
                inb = inb * 0.0174532925;
            }
            out = Math.cos(inb);
        } else {
            txtDisplay2.setText("cosh( " + String.valueOf(inb) + ")");
            out = Math.cosh(inb);
        }
        txtDisplay1.setText(String.valueOf(out));
        
        out = 0;
        op =0;
    }//GEN-LAST:event_btnCosActionPerformed

    private void btnTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTanActionPerformed
        inb = Double.parseDouble(String.valueOf(txtDisplay1.getText()));
        if (!shift) {
            if (!dgrrad) {
                txtDisplay2.setText("tan( " + String.valueOf(inb) + ")");
                inb = inb * 0.0174532925;
            }
            out = Math.tan(inb);
        } else {
            txtDisplay2.setText("tanh( " + String.valueOf(inb) + ")");
            out = Math.tanh(inb);
        }
        txtDisplay1.setText(String.valueOf(out));
        
        out = 0;
        op = 0  ;
    }//GEN-LAST:event_btnTanActionPerformed

    private void rdoDagreesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoDagreesActionPerformed
        dgrrad = false;
    }//GEN-LAST:event_rdoDagreesActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (op == 0) {
            ina = Double.parseDouble(String.valueOf(txtDisplay1.getText()));
        } else {
            inb = Double.parseDouble(String.valueOf(txtDisplay1.getText()));
        }
        if (op == 1) {
            ina = ina + inb;
        }
        if (op == 2) {
            ina = ina - inb;
        }
        if (op == 3) {
            ina = ina * inb;
        }
        if (op == 4) {
            ina = ina / inb;
        }
        if (op == 5) {
            ina = ina * inb / 100;
        }
        txtDisplay1.setText("0");
        txtDisplay2.setText(String.valueOf(ina) + " + ");

        op = 1;

        desdisp = false;
        zerodisp = false;
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSubstracActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubstracActionPerformed
        if (op == 0) {
            ina = Double.parseDouble(String.valueOf(txtDisplay1.getText()));
        } else {
            inb = Double.parseDouble(String.valueOf(txtDisplay1.getText()));
        }
        if (op == 1) {
            ina = ina + inb;
        }
        if (op == 2) {
            ina = ina - inb;
        }
        if (op == 3) {
            ina = ina * inb;
        }
        if (op == 4) {
            ina = ina / inb;
        }
        if (op == 5) {
            ina = ina * inb / 100;
        }
        txtDisplay1.setText("0");
        txtDisplay2.setText(String.valueOf(ina) + " - ");

        op = 2;

        desdisp = false;
        zerodisp = false;
    }//GEN-LAST:event_btnSubstracActionPerformed

    private void btnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplyActionPerformed
        if (op == 0) {
            ina = Double.parseDouble(String.valueOf(txtDisplay1.getText()));
        } else {
            inb = Double.parseDouble(String.valueOf(txtDisplay1.getText()));
        }
        if (op == 1) {
            ina = ina + inb;
        }
        if (op == 2) {
            ina = ina - inb;
        }
        if (op == 3) {
            ina = ina * inb;
        }
        if (op == 4) {
            ina = ina / inb;
        }
        if (op == 5) {
            ina = ina * inb / 100;
        }
        txtDisplay1.setText("0");
        txtDisplay2.setText(String.valueOf(ina) + " * ");

        op = 3;

        desdisp = false;
        zerodisp = false;
    }//GEN-LAST:event_btnMultiplyActionPerformed

    private void btnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivideActionPerformed
        if (op == 0) {
            ina = Double.parseDouble(String.valueOf(txtDisplay1.getText()));
        } else {
            inb = Double.parseDouble(String.valueOf(txtDisplay1.getText()));
        }
        if (op == 1) {
            ina = ina + inb;
        }
        if (op == 2) {
            ina = ina - inb;
        }
        if (op == 3) {
            ina = ina * inb;
        }
        if (op == 4) {
            ina = ina / inb;
        }
        if (op == 5) {
            ina = ina * inb / 100;
        }
        txtDisplay1.setText("0");
        txtDisplay2.setText(String.valueOf(ina) + " / ");

        op = 4;

        desdisp = false;
        zerodisp = false;
    }//GEN-LAST:event_btnDivideActionPerformed

    private void btnPercentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPercentActionPerformed
        ina = Double.parseDouble(String.valueOf(txtDisplay1.getText()));
        txtDisplay1.setText("0");
        txtDisplay2.setText(String.valueOf(ina)+ "% ( ");

        desdisp = false;
        zerodisp = false;

        op = 5;
    }//GEN-LAST:event_btnPercentActionPerformed

    private void btnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualActionPerformed
        inb = Double.parseDouble(String.valueOf(txtDisplay1.getText()));

        if (op == 0) {
            out = inb;
            txtDisplay2.setText(String.valueOf(inb));
        }

        if (op == 1) {
            out = ina + inb;
            txtDisplay2.setText(txtDisplay2.getText() + String.valueOf(inb));
        }
        if (op == 2) {
            out = ina - inb;
            txtDisplay2.setText(txtDisplay2.getText() + String.valueOf(inb));
        }
        if (op == 3) {
            out = ina * inb;
            txtDisplay2.setText(txtDisplay2.getText() + String.valueOf(inb));
        }
        if (op == 4) {
            out = ina / inb;
            txtDisplay2.setText(txtDisplay2.getText() + String.valueOf(inb));
        }
        if (op == 0) {
            out = ina * inb / 100;
            txtDisplay2.setText(txtDisplay2.getText() + String.valueOf(inb) + ")");
        }
        if (out > -100000000 && out < 100000000) {
            txtDisplay1.setText(String.valueOf(out));
        } else {
            txtDisplay1.setText("Error");
        }

        ina = 0;
        inb = 0;
        out = 0;

        op = 0;
        desdisp =false;
        zerodisp = false;
        
        

    }//GEN-LAST:event_btnEqualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton TbtnShift;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCos;
    private javax.swing.JButton btnCubed;
    private javax.swing.JButton btnCubedRoot;
    private javax.swing.JButton btnDecPoint;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnEight;
    private javax.swing.JButton btnEqual;
    private javax.swing.JButton btnFive;
    private javax.swing.JButton btnFour;
    private javax.swing.JButton btnMemory;
    private javax.swing.JButton btnMemoryClear;
    private javax.swing.JButton btnMemorySave;
    private javax.swing.JButton btnMultiply;
    private javax.swing.JButton btnNegace;
    private javax.swing.JButton btnNine;
    private javax.swing.JButton btnOne;
    private javax.swing.JButton btnOneDividedByx;
    private javax.swing.JButton btnPercent;
    private javax.swing.JRadioButton btnRadians;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSeven;
    private javax.swing.JButton btnSin;
    private javax.swing.JButton btnSix;
    private javax.swing.JButton btnSquare;
    private javax.swing.JButton btnSquareRoot;
    private javax.swing.JButton btnSubstrac;
    private javax.swing.JButton btnTan;
    private javax.swing.JButton btnThree;
    private javax.swing.JButton btnTwo;
    private javax.swing.JButton btnZero;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JRadioButton rdoDagrees;
    private javax.swing.JTextField txtDisplay1;
    private javax.swing.JTextField txtDisplay2;
    private javax.swing.JTextField txtmemoryDisplay;
    // End of variables declaration//GEN-END:variables
}
